# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Search version
      run: |
        export PROJECT_VERSION_VALUE=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo $PROJECT_VERSION_VALUE
        echo '::set-env name=PROJECT_VERSION::'$PROJECT_VERSION_VALUE-$(date +'%Y%m%d%H%M%S')
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ env.PROJECT_VERSION }}
        release_name: Release ${{ env.PROJECT_VERSION }}
        body: |
         Nova release
           - Features novas
           - Ajuste de bugs
        draft: false
        prerelease: false
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml -Dmaven.test.skip=true
      env:
        GITHUB_TOKEN: ${{ github.token }}
